package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GUI {
    private JLabel labelNumber;
    private JPanel panel1;
    private JLabel labelSeed;
    private JTextField textFieldNumber;
    private JTextField textFieldSeed;
    private JLabel labelCapacity;
    private JTextField textFieldCapacity;
    private JButton buttonSolve;
    private JTextArea textAreaInstance;
    private JTextArea textAreaResult;
    private JLabel labelInstance;
    private JLabel labelResults;


    public GUI() {
        buttonSolve.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean allValid = true;
                if (textFieldNumber.getText().isEmpty() || textFieldSeed.getText().isEmpty() || textFieldCapacity.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please fill all the fields");
                } else {
                    try {
                        Problem problem = new Problem(Integer.parseInt(textFieldNumber.getText()), Integer.parseInt(textFieldSeed.getText()), 1, 10);
                        textAreaInstance.setText(problem.toString());
                        Result result = problem.Solve(Integer.parseInt(textFieldCapacity.getText()));
                        textAreaResult.setText(result.toString());
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Please enter valid numbers");
                    }
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("KnapsackGUI");
        frame.setContentPane(new GUI().panel1);
        frame.setPreferredSize(new Dimension(800, 600));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        labelNumber = new JLabel();
        labelNumber.setHorizontalAlignment(2);
        labelNumber.setHorizontalTextPosition(2);
        labelNumber.setText("Number of types of items:");
        labelNumber.setVerticalAlignment(1);
        labelNumber.setVerticalTextPosition(1);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(labelNumber, gbc);
        labelSeed = new JLabel();
        labelSeed.setText("Seed:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(labelSeed, gbc);
        textFieldNumber = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textFieldNumber, gbc);
        textFieldSeed = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textFieldSeed, gbc);
        labelCapacity = new JLabel();
        labelCapacity.setText("Capacity:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(labelCapacity, gbc);
        buttonSolve = new JButton();
        buttonSolve.setLabel("Solve");
        buttonSolve.setText("Solve");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(buttonSolve, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.weighty = 2.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        textAreaInstance = new JTextArea();
        textAreaInstance.setEditable(false);
        textAreaInstance.setRows(5);
        textAreaInstance.setText("This box shows instance of a problem.");
        scrollPane1.setViewportView(textAreaInstance);
        textFieldCapacity = new JTextField();
        textFieldCapacity.setText("");
        textFieldCapacity.setToolTipText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textFieldCapacity, gbc);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 8;
        gbc.weightx = 2.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane2, gbc);
        textAreaResult = new JTextArea();
        textAreaResult.setEditable(false);
        textAreaResult.setText("This box shows the solution to the problem.");
        scrollPane2.setViewportView(textAreaResult);
        labelInstance = new JLabel();
        labelInstance.setText("Instance:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(labelInstance, gbc);
        labelResults = new JLabel();
        labelResults.setHorizontalAlignment(10);
        labelResults.setHorizontalTextPosition(11);
        labelResults.setText("Results:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel1.add(labelResults, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
